### ISSUE TITLE
Unclear bug - noting for later

### ISSUE THREAD

**Issue by pgibler** [pgibler/cmdh#1]
```
gibler@gibler-MS-7D43:~$ cmdh 'Continously monitor all in-use socket connections.'
✔ Retrieving command... Continously monitor all in-use socket connections.
setup commands: [ sudo apt-get install net-tools -y ]
main command: watch -n 1 "netstat -tunap"
assistant message: The above command will continuously monitor all in-use socket connections every second. Please note that this command is designed for an interactive shell and may not work as expected if run in a non-interactive shell.
? Choose an option:node:internal/readline/emitKeypressEvents:74
            throw err;A)
            ^ commands (S)
>   Copy command to clipboard (C)
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at file:///home/gibler/Code/Public/cmdh/src/customListPrompt.mjs:30:96
    at Array.findIndex (<anonymous>)
    at file:///home/gibler/Code/Public/cmdh/src/customListPrompt.mjs:30:34
    at ReadStream.handler (file:///home/gibler/Code/Public/cmdh/node_modules/@inquirer/core/dist/esm/index.mjs:58:13)
    at ReadStream.emit (node:events:524:35)
    at emitKeys (node:internal/readline/utils:360:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (node:internal/readline/emitKeypressEvents:64:36)
    at ReadStream.emit (node:events:512:28)
    at addChunk (node:internal/streams/readable:324:12)

Node.js v19.7.0
```

**Comment by pgibler** [comment]
Haven't seen this since April, closing unless it happens again
