### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by tofasthacker** [pgibler/cmdh#12]
I am having trouble getting this tool to work on my computer. I have node v12.22.12 installed and when ever I run the cmdh.sh file I get the following error.

```
$ ./cmdh.sh configure
file:///home/brickman/cmdh/src/run.mjs:187
await main();
^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```

I really appreciate the work you are doing and any help would be appreciated.

**Comment by tofasthacker** [comment]
I figure out the problem. I was using an out of date version of node js. A simple node js update fixed my problems.
